server:
  port: ${PORT:8080}
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  pluginsDir: "./plugins"
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # Disabled because using the YouTube plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
      spotify: false

    filters:
      volume: false
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false

    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEB_EMBEDDED  # ✅ Fixed from "WEBEMBEDDED"
    email: "your-email@gmail.com"           # ✅ Replace with real Gmail
    password: "your-app-password"           # ✅ App password from Google

  lavasrc:
    sources:
      youtube: false
      spotify: true
      deezer: false
      apple: false
    spotify:
      clientId: "your_spotify_client_id"       # ✅ Replace from Spotify Developer Dashboard
      clientSecret: "your_spotify_client_secret"
      countryCode: "IT"
      playlistLoadLimit: 1000
      albumLoadLimit: 1000

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
